# Generated by Django 6.0 on 2025-12-09 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название материала')),
                ('current_quantity', models.FloatField(default=0, verbose_name='Текущее количество')),
                ('min_threshold', models.FloatField(default=10, verbose_name='Минимальный порог')),
                ('unit', models.CharField(default='шт.', max_length=20, verbose_name='Ед. измерения')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='UsageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('quantity_used', models.FloatField(verbose_name='Расход')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Запись расхода',
                'verbose_name_plural': 'История расходов',
            },
        ),
    ]
