# Generated by Django 6.0 on 2025-12-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_material_article_number_material_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='article_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='material',
            name='unit',
            field=models.CharField(choices=[('шт.', 'Штуки'), ('кг', 'Килограммы'), ('л', 'Литры'), ('м', 'Метры')], default='шт.', max_length=5, verbose_name='Ед. измерения'),
        ),
    ]
