# Generated by Django 6.0 on 2025-12-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_alter_material_article_number_alter_material_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagehistory',
            options={'ordering': ['-date'], 'verbose_name': 'История использования', 'verbose_name_plural': 'История использования'},
        ),
    ]
