# Generated by Django 6.0 on 2025-12-11 17:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_alter_usagehistory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usagehistory',
            options={'ordering': ['-date'], 'verbose_name': 'История операций', 'verbose_name_plural': 'История операций'},
        ),
        migrations.RemoveField(
            model_name='usagehistory',
            name='quantity_used',
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='operation_type',
            field=models.CharField(choices=[('IN', 'Приход (Закупка)'), ('OUT', 'Расход (Продажа/Производство)'), ('DISP', 'Списание (Брак/Просрочка)')], default=1, max_length=5, verbose_name='Тип операции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usagehistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='usagehistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
    ]
