# Generated by Django 6.0 on 2025-12-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_alter_usagehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagehistory',
            name='operation_type',
            field=models.CharField(choices=[('IN', 'Приход (Закупка)'), ('OUT', 'Расход (Продажа/Производство)'), ('DISP', 'Списание (Брак/Просрочка)')], default='OUT', max_length=4, verbose_name='Тип операции'),
        ),
    ]
