# Generated by Django 6.0 on 2025-12-12 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0007_alter_usagehistory_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagehistory',
            name='operation_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата операции'),
        ),
    ]
