# Generated by Django 6.0 on 2025-12-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_usagehistory_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagehistory',
            name='operation_type',
            field=models.CharField(choices=[('IN', 'Приход (Закупка)'), ('OUT', 'Расход (Выдача)'), ('DISP', 'Списание (Брак/Просрочка)')], default='OUT', max_length=4, verbose_name='Тип операции'),
        ),
    ]
